import { createSlice } from "@reduxjs/toolkit";

export const initialState = {
  mainPosts: [],
  singlePost: null,
  imagePaths: [],
  updateImagePaths: [],
  hasMorePost: true,
  loadPostsLoading: false,
  loadPostsDone: false,
  loadPostsError: null,
  loadHashtagPostsLoading: false,
  loadHashtagPostsDone: false,
  loadHashtagPostsError: null,
  loadUserPostsLoading: false,
  loadUserPostsDone: false,
  loadUserPostsError: null,
  loadPostLoading: false,
  loadPostDone: false,
  loadPostError: null,
  updatePostLoading: false,
  updatePostDone: false,
  updatePostError: null,
  addPostLoading: false,
  addPostDone: false,
  addPostError: null,
  removePostLoading: false,
  removePostDone: false,
  removePostError: null,
  uploadImagesLoading: false,
  uploadImagesDone: false,
  uploadImagesError: null,
  updateImagesLoading: false,
  updateImagesDone: false,
  updateImagesError: null,
  removeImageLoading: false,
  removeImageDone: false,
  removeImageError: null,
  addCommentLoading: false,
  addCommentDone: false,
  addCommentError: null,
  retweetLoading: false,
  retweetDone: false,
  retweetError: null,
  addLikeLoading: false,
  addLikeDone: false,
  addLikeError: null,
  removeLikeLoading: false,
  removeLikeDone: false,
  removeLikeError: null,
  addReportLoading: false,
  addReportDone: false,
  addReportError: null,
  loadReportsLoading: false,
  loadReportsDone: false,
  loadReportsError: null,
  postAppealLoading: false,
  postAppealDone: false,
  postAppealError: null,
};

const postSlice = createSlice({
  name: "post",
  initialState,
  reducers: {},
  extraReducers: {},
});

export default postSlice;
